spring:
  batch:
    initialize-schema: always
    job:
      names: "jpaJob"
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/imdb_new
    username: postgres
    password: postgres
legacy:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/imdb_legacy
      username: postgres
      password: postgres
#test:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5433/batch_schema
#    username: postgres
#    password: postgres