spring:
  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imdb_tsv
    username: postgres
    password: postgres
#    initialization-mode: always
#  batch:
#    initialize-schema: always
