spring:
  datasource:
#    platform: org.hibernate.dialect.PostgreSQLDialect
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/novo
    username: postgres
    password: postgres
#    initialization-mode: always
#testee:
#  datasource:
#    platform: org.hibernate.dialect.PostgreSQLDialect
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/imdb_tsv
#    username: postgres
#    password: postgres
  batch:
    initialize-schema: always
